title:
  patterns:
    - '^.{0,54}$'
  error: 'The title must be 54 characters or shorter'
body:
  patterns:
    - '.+'
  error: The body can not be empty
reviewers:
  minimum: 1
labels:
  - bug
  - enhancement
