name: Prace
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Prace
        uses: ./ # Uses an action in the root directory
        with:
          configuration-path: .github/prace.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
